#Azure Pipeline AKS

trigger:
- main

resources:
- repo: self

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      name: devpool
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'docker'
        repository: 'sebastifalck/dotnet'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(Pipeline.Workspace)/s/aspnet-mssql/environment'
        artifact: 'environment'
        publishLocation: 'pipeline'

- stage: Bash
  displayName: Hola mundo
  dependsOn: Build
  jobs:
  - job: Bash
    displayName: Bash
    pool:
      name: devpool
    steps:    
    - task: PowerShell@2
      inputs:
        targetType: 'inline'
        script: |
          for ($i = 1; $i -le 10; $i++) {
            Write-Host "Hola Mundo"
          }

- stage: Bash2
  displayName: Create .txt
  dependsOn: Build
  jobs:
  - job: Bash
    displayName: Bash
    pool:
      name: devpool
    steps:
    - task: PowerShell@2
      inputs:
        targetType: 'inline'
        script: |
          for ($i = 1; $i -le 10; $i++) {
            $date = Get-Date -Format 'yyyy-MM-dd'
            $fileName = "file$i.txt"
            New-Item -Path $fileName -ItemType File
            Add-Content -Path $fileName -Value $date
            Write-Host "Created $fileName with date: $date"
                }