apiVersion : apps/v1
kind: Deployment
metadata:
  name: dotnet
  namespace: kubernetes
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dotnet
  template:
    metadata:
      labels:
        app: dotnet
    spec:
      containers:
        - name: dotnet
          image: sebastifalck/dotnet:58
          env:
          - containerPort: 80
    selector:
      matchLabels:
        app: dotnet
---
apiVersion: v1
kind: Service
metadata:
  name: dotnet
  namespace: kubernetes
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: dotnet