apiVersion : apps/v1
kind: Deployment
metadata:
  name: dotnet
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dotnet
  template:
    metadata:
      labels:
        app: dotnet
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: agentpool
                    operator: In
                    values:
                      - agentpool
      containers:
        - env:
          image: sebastifalck/dotnet:58
          name: dotnet
          ports:
          - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: dotnet
  namespace: kubernetes
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: dotnet