apiVersion : apps/v1
kind: Deployment
metadata:
  name: dotnet
  namespace: kubernetes
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dotnet
  template:
    metadata:
      labels:
        app: dotnet
    spec:
      containers:
        - name: dotnet
          image: sebastifalck/dotnet:58
          env:
          - name: ASPNETCORE_URLS
            value: http://*:80
          - containerPort: 80
    selector:
      matchLabels:
        app: dotnet
---
apiVersion: v1
kind: Service
metadata:
  name: dotnet
spec:
  type: Cluster IP
  ports:
  - port: 80
  selector:
    app: dotnet